### ISSUE TITLE
Add IDs to sourceTypes

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-RestApi#102]
It would be great if we could have an ID in the `sourceTypes` object.  
With IDs the data from the subjects API and the sourceTypes API would be easier to merge.

**Comment by yatharthranjan** [comment]
Yes sourceTypes do have an id from the MP api so can be easily implemented. I will look into it.

**Comment by herkulano** [comment]
After the merge, the IDs are shown in the subjects but not in `https://radar-backend.co.uk/api/source-types/EMPATICA/E4/1.0.0` and `https://radar-backend.co.uk/api/source-types`.

**Comment by yatharthranjan** [comment]
Hi Herc, the latest rest api is not deployed yet. I will deploy it now. 

Edit: Done -- It works now

**Comment by yatharthranjan** [comment]
Fixed in #103
