### ISSUE TITLE
Duplicate key SourceTypeDTO (500 Error)

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-RestApi#104]
Error in API: `https://radar-backend.co.uk/api/projects/BioIT-Demo/subjects`

```
{error: "server_error", message: "class java.lang.IllegalStateException: Duplicate key SourceTypeDTO{ producer='THINCIT IIRC', model='THINCIT', catalogVersion='1.0.0', sourceTypeScope='ACTIVE', canRegisterDynamically='true', name='THINCIT', description=ThincIt Cognition in Depression app., appProvider=null, assessmentType=null}."}
```

**Comment by yatharthranjan** [comment]
Hi Herc, can you try again now?. It was inserted as a duplicate id probably because of an attempt of migration to another postgres docker image version.
I have manually removed the duplicate records from the database.

**Comment by herkulano** [comment]
@yatharthranjan works! 💯
