### ISSUE TITLE
403 permission error on data API

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-RestApi#106]
"Http failure response for https://radar-backend.co.uk/api/data/BioIT-Demo/3907dab9-b2ae-4db1-ba93-d5b3f699b1eb/b6f1a0bb-b663-4aa2-a776-3a51d4dc5f86/EMPATICA_E4_1.0.0_BATTERY/AVERAGE?timeWindow=TEN_SECOND: 403 OK"

**Comment by yatharthranjan** [comment]
I just tested it and its working now.
