### ISSUE TITLE
Sort datasets

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-RestApi#108]
Datasets should be sorted by timeStart. Currently, MongoDB does not sort them.

**Comment by blootsvoets** [comment]
It looks like the datasets should be sorted
https://github.com/RADAR-base/RADAR-RestApi/blob/0b855a1781d37036f8285134d3b370f62c7177e7/src/main/java/org/radarcns/mongo/util/MongoHelper.java#L117
We should investigate why this is not the case.

**Comment by yatharthranjan** [comment]
Yes thats what i found out. Maybe indexing is the issue here ?

**Comment by blootsvoets** [comment]
Should be fixed by #109 and #111, but it still needs to be tested.

**Comment by yatharthranjan** [comment]
Okay on it

**Comment by nivemaham** [comment]
I have tested the fix on test env and the records are sorted on timeStart now
