### ISSUE TITLE
The latest API from dev branch gives error

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-RestApi#119]
The following error is thrown --

```
Cannot deserialize instance of java.util.LinkedHashMap out of START_OBJECT token at [Source: (StringReader); line: 1, column: 32087] (through reference chain: java.util.ArrayList[0]>org.radarcns.domain.managementportal.ProjectDTO["attributes"])
```

**Comment by nivemaham** [comment]
which version of MP are you using? Please note latest dev is MP 0.4.0 compatible #117 .You need to use compatible MP version or an older rest-api version if not migrated to Mp 0.4.0

**Comment by yatharthranjan** [comment]
Oh okay i see. Yes i am using 0.3.6. Thanks
