### ISSUE TITLE
Interval field

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-RestApi#17]
Add an `interval` input variable to specify time window granularity. If not specified, it should return the smallest time granularity available for the given user.

Suggested values are

- 10 seconds
- 30 seconds
- 1 min
- 10 min
- 1 hour
- 1 day
- 1 week

**Comment by fnobilia** [comment]
@herkulano are the intervals correct?

I will create an enumerator to define them. Something like:
```JSON
{
  "namespace": "org.radarcns.avro.restapi",
  "type": "enum",
  "name": "Interval",
  "symbols": [
    "TEN_SEC" , "THIRTY_SEC", "ONE_MIN", "TEN_MIN", "ONE_H", "ONE_DAY", "ONE_WEEK"
  ]
}
```

**Comment by herkulano** [comment]
From what we have in the UI yes. 
Why not use `ms`? Will you return the interval in `ms` or as these strings? If the latter, it means we have to have a table of the strings and corresponding values in `ms`, which is not a good idea.

@kerzmaximilian can you confirm the intervals?

**Comment by fnobilia** [comment]
With an enumerator we can define a domain for `interval` and exclude any ambiguity.

The smallest time frame we have is 10 seconds, if a user request frame of 13 seconds shall we provide frame of 10 or 20 seconds? For avoid this issue, an enumerator could help us.

Since only letters can be used to name constants according to the [Google style code](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names), the above one was the result.

As usual, open to update it, change it or move to another approach!

**Comment by herkulano** [comment]
That's cool as long as you send also the `ms` values also. 
Otherwise, if there are any changes to these constants the frontend needs to be updated also.

**Comment by afolarin** [comment]
Time-series data for each interval should be cached in the hot storage, however this imposes specific limits on the data that can be returned for a arbitrary request for a given time window.

I discussed with @fnobilia about how requests for out of phase windows should be handled. We thought that this should be parameterised to return the closest | lower-bound | upper-bound, so the requester can choose preference to return slightly too much or too little data. 

If needed it one might also consider including an option to compute the data on the fly for special case applications that need this behaviour?
