### ISSUE TITLE
Provide abstraction layer for identity server

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/RADAR-RestApi#24]
Idea from discussion with @fnobilia: Provide an abstraction layer for commonly used tasks on the identity server. From a security perspective this hides the actual identity product. From an implementation perspective, it decouples all clients from the specific identity server product. Tasks to provide:

- Provision a new user
- Set user roles
- Set user affiliation with projects and studies
- Get a valid token
- Renew a token
- Validate a token
- Get user roles and project/study affiliations
- Others?

**Comment by dennyverbeeck** [comment]
I have given this a bit more thought, i think we should move this to be it's own service. Reasons are: in terms of security, this api does probably not need to be public-facing, but can be on internal networks only. More adherence to micro-services architecture, separating responsibilities of services. I suggest moving this to a new repo RADAR-Identity-Api. Any thoughts?

**Comment by fnobilia** [comment]
Shall these two
- Renew a token
- Validate a token

make public?

**Comment by dennyverbeeck** [comment]
Good point, the token operations should be public. And actually the user operations as well, since we want an authenticated admin at the dashboard to be able to manage users and studies. Ok so it should not be on internal networks only. In that case it might not be worth factoring these operations out of rest-api :)

**Comment by dennyverbeeck** [comment]
Will close this because we have [ManagementPortal](https://github.com/RADAR-CNS/ManagementPortal) now
