### ISSUE TITLE
API rate limiting (quotas)

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-RestApi#25]
When Cold Storage will be integrated with the REST API, we could design a mechanism to limit CPU-burst operations.

**Comment by blootsvoets** [comment]
What do you mean by that? Some caching mechanism for data retrieved by the REST API from HDFS?

**Comment by fnobilia** [comment]
Quoting this [blog spot](https://stripe.com/blog/rate-limiters)

> Rate limiting can help make your API more reliable in the following scenarios:
> 
> - One of your users is responsible for a spike in traffic, and you need to stay up for everyone else.
> 
> - One of your users has a misbehaving script which is accidentally sending you a lot of requests. Or, even worse, one of your users is intentionally trying to overwhelm your servers.
> 
> - A user is sending you a lot of lower-priority requests, and you want to make sure that it doesn’t affect your high-priority traffic. For example, users sending a high volume of requests for analytics data could affect critical transactions for other users.
> 
> - Something in your system has gone wrong internally, and as a result you can’t serve all of your regular traffic and need to drop low-priority requests.

At present there is no requirement to provide this. In the future, this might be a valuable enhancement.

**Comment by blootsvoets** [comment]
Ah okay. So its about REST API rate limiting. I've updated the title of the issue accordingly.

**Comment by blootsvoets** [comment]
It would probably be better to implement this in a nginx frontend. See https://www.nginx.com/blog/rate-limiting-nginx/.
