### ISSUE TITLE
Realtime value directly from Kafka Stream

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-RestApi#28]
Analyse whether it is possible to extract the last computed value directly from `Kafka Stream` instead of querying`MongoDb`[[Reference](https://www.confluent.io/blog/getting-started-with-the-kafka-streams-api-using-confluent-docker-image/)]

**Comment by afolarin** [comment]
Perhaps keep an eye on this Confluence project KSQL.
https://www.confluent.io/product/ksql/
https://github.com/confluentinc/ksql

**Comment by blootsvoets** [comment]
KSQL is interesting for the backend, but for simplicity, I'd leave it out of the REST API for now.
