### ISSUE TITLE
Disambiguate HeartRateDataset Dataset

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-RestApi#3]
@fnobilia 

RADAR-RestApi/src/main/resources/avro/heart_rate_dataset.avsc
```
"items": [ "HeartRateItem" , "QuartilesItem" ]}
```
should broken so multiple types are not represented by multiple types

**Comment by fnobilia** [comment]
The natural solution is to define a custom schema just for the quartile, since all other values fit the already available `RADAR-RestApi/src/main/resources/avro/heart_rate.avsc`

**Comment by afolarin** [comment]
OK good. So HeartRateDataset allows single and multiple values
