### ISSUE TITLE
Include studyID parameter in all subject-level data requests

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/RADAR-RestApi#32]
Subjects could end up being part of multiple studies. This will disambiguate which data is being requested.

**Comment by dennyverbeeck** [comment]
Actually, since user roles are study specific, the studyID should probably be present in all requests.

**Comment by yatharthranjan** [comment]
@dennyverbeeck Since the subject info is now retrieved from MP and it has the project info with it so I think we can close this ?

**Comment by dennyverbeeck** [comment]
Agreed!
