### ISSUE TITLE
Start and end times of response

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-RestApi#37]
When the request has defined start and end times the response should have the same start and end times in the header.

```
api/data/BATTERY/AVERAGE/TEN_SECOND/MRC01/00:07:80:1F:52:F3/1497589120000/1497628000000
```

current response:
```json
{
  "header": {
    "subjectId": "MRC01",
    "sourceId": "00:07:80:1F:52:F3",
    "source": "EMPATICA",
    "sensor": "BATTERY",
    "descriptiveStatistic": "AVERAGE",
    "unit": "PERCENTAGE",
    "timeFrame": "TEN_SECOND",
    "effectiveTimeFrame": {
      "startDateTime": "2017-06-16T08:59:40Z",
      "endDateTime": "2017-06-16T12:04:20Z"
    }
  },
  "dataset": [
    {
      "sample": {
        "value": 0.48716214
      },
      "startDateTime": "2017-06-16T08:59:40Z"
    },
    {
      "sample": {
        "value": 0.10312305642857143
      },
      "startDateTime": "2017-06-16T12:04:10Z"
    }
  ]
}
```

```
1497589120000 === "2017-06-16T04:58:40.000Z"
1497628000000 === "2017-06-16T15:46:40.000Z"
```

```json
"effectiveTimeFrame": {
"startDateTime": "2017-06-16T04:58:40.000Z",
"endDateTime": "2017-06-16T04:58:40.000Z"
}

```

TODO
  - [ ] start and end times in response should match request
  - [ ] "timeFrame": "TEN_SECOND" should report the timeFrame of the request not default "TEN_SECOND"

**Comment by herkulano** [comment]
For clarity, the response object should look like this:
```
{
  "header": {
    "subjectId": "MRC01",
    "sourceId": "00:07:80:1F:52:F3",
    "source": "EMPATICA",
    "sensor": "BATTERY",
    "descriptiveStatistic": "AVERAGE",
    "unit": "PERCENTAGE",
    "timeWindow": "TEN_SECOND", // changed, discussed here: https://github.com/RADAR-CNS/RADAR-RestApi/issues/38#issuecomment-331805338
    "timeFrame": {
      "startDateTime": "2017-06-16T04:58:40.000Z",
      "endDateTime": "2017-06-16T15:46:40.000Z"
    }    
    "effectiveTimeFrame": {
      "startDateTime": "2017-06-16T08:59:40Z",
      "endDateTime": "2017-06-16T12:04:20Z"
    }
  },
  "dataset": [
    {
      "sample": {
        "value": 0.48716214
      },
      "startDateTime": "2017-06-16T08:59:40Z"
    },
    {
      "sample": {
        "value": 0.10312305642857143
      },
      "startDateTime": "2017-06-16T12:04:10Z"
    }
  ]
}
```

Where the `timeFrame` is the requested time frame and the `effectiveTimeFrame` is the time frame that effectively has data. `effectiveTimeFrame` is always within the boundaries of the `timeFrame` requested.

**Comment by nivemaham** [comment]
@herkulano , in the above example of response, what is the difference between `timeFrame` and `effectiveTimeFrame`? . Currently, we provide only `effectiveTimeFrame` which would reflect the values in the request if provided, otherwise the earliest and latest time stamp fetched from the records of that request.

**Comment by herkulano** [comment]
@nivemaham 
> `timeFrame` is the requested time frame and the `effectiveTimeFrame` is the time frame that effectively has data. `effectiveTimeFrame` is always within the boundaries of the `timeFrame` requested.

What I mean is that `timeFrame` is the time frame requested: `api/data/BATTERY/AVERAGE/TEN_SECOND/MRC01/00:07:80:1F:52:F3/1497589120000/1497628000000`

The `effectiveTimeFrame` is the time frame that is contained by the data, i.e., the requested `timeFrame` might be `10:00:00/11:00:00` but the data effectively only exists is in the following time frame: `10:20:00/10:40:00`

In practice, the `timeFrame` doesn't exist in the backend, it's sent in the response. The backend takes the request time frame parameters and adds them to the response.

**Comment by nivemaham** [comment]
@herkulano Is that really necessary? What should be the values for `timeFrame` when you send to get a request to fetch the `latest` and `all` records that are available?

**Comment by blootsvoets** [comment]
For `all` records, perhaps the timeFrame can be `null`? For `latest`, don't we keep an internal timeframe (like records that arrived 10 minutes ago up till now?) That would be a proper time frame.

**Comment by nivemaham** [comment]
@blootsvoets I am not sure which internal timeframe you are referring to. But i think if the intention of having another attribute as `timeFrame` to reflect what was requested, we can make use of the timeWindow used in the request and calculate a timeFrame from (now - TimeWindow). Would that work?

**Comment by blootsvoets** [comment]
For example, yes.

**Comment by herkulano** [comment]
@nivemaham 

> Is that really necessary?

Not strictly necessary. It makes it a lot easier to manage the state in the frontend, thought this would be trivial on the backend.

Agree with @blootsvoets on how it should behave on `all` and `latest` records.

**Comment by nivemaham** [comment]
@herkulano . Ok. No problem. It is already implemented.
