### ISSUE TITLE
Use Inject and Context instead of singletons

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-RestApi#41]
Right now, `getInstance` is used a lot on database handler. An `@Inject` syntax like explained in <https://stackoverflow.com/a/29275727/574082> would be more transparent and less prone to multithreading issues. By using scope `PerThread`, a database connection per thread could be maintained.

**Comment by blootsvoets** [comment]
Partially changed in #69, more changes are needed for example the source catalog, monitors and DOA.

**Comment by nivemaham** [comment]
@blootsvoets Can we close this now?

**Comment by blootsvoets** [comment]
Indeed
