### ISSUE TITLE
Embedded Jetty for Rest-api

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-RestApi#57]
@blootsvoets @yatharthranjan 
Since we are already doing some refactoring, can we also change REST-APi packaging with an embedded-jettty rather than deploying on  external Tomcat?
What is your opinion?

**Comment by blootsvoets** [comment]
I like the idea, but it will require really quite a bit more refactoring, and Tomcat is behaving fine for us now.

Something not Tomcat related but general is that static classes and methods are used all over the place, and method calls are hidden behind four layers of helper functions. I'd prefer to handle that first so we get a grip on the complexity, and then after that we can think of changing the servlet engine. We're already using Jersey+HK2 for injection if needed.

**Comment by yatharthranjan** [comment]
I am really on board with the idea but agree with @blootsvoets. We have to focus on other things right now required for the dashboard. Maybe keep this as a future target ?

**Comment by blootsvoets** [comment]
Using Grizzly now, which made using the HK2 functionality much easier.
