### ISSUE TITLE
Response code structure 

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-RestApi#60]
Can we document what would be the best response structure for each entity involved in Rest-API here?
E.g. are we going to return the old structure for source-> source-summary. 
What should be the response code when `api/subjects/sub-1` and no subject found under given subject-id?
Following the latest rest-api design, i would say it can be `404 : Not Found`, But the documentations day `204 : No Content`. 
Any thoughts on this?
@blootsvoets @yatharthranjan

**Comment by blootsvoets** [comment]
Yes, I agree.

In general, 204 should be used as response to PUT, POST or DELETE requests, not GET requests. Either respond
1. that the request was successful (code 200) with a valid JSON response and valid JSON header and an empty JSON dataset (for example, when selecting on a time frame) or
2. with not found (code 404) if a given entity does not exist and the caller would know this from an earlier request (e.g., GET `/subjects`).

**Comment by nivemaham** [comment]
Provided that we have a common agreement on response codes i think we can close this issue. The api and response structures can be followed in #63
