### ISSUE TITLE
Study project name improvement

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-RestApi#98]
The Study object could be improved by having a property with the "pretty" name of the project that allows spaces and keeps the text casing, while also improving the slug to be always lowercase and replacing spaces with hyphens.

Proposal:
```ts
export interface Study {
  id: number | string
  projectName: string // "pretty" name: "Radar BioIT Demo"
  projectId: string // slug: "radar-bioit-demo"
  ...
}
```

//cc @kerzmaximilian @blootsvoets

**Comment by nivemaham** [comment]
Valid request. But it should be taken care at the MP side. I will create an issue there
